//GLB MODELS

export const exploreList = [
  {
    name: 'Parajumpers',
    productName: 'Janet Puffer Coat',
    price: '745',
    src: 'https://shop.futugoapp.com/cdn/shop/products/45660_137472.jpg?v=1693926500&width=720',
    size: 'S',
    color: 'Nude',
    composition: [
      'Stay warm and stylish with the Parajumpers Janet Oversized Puffer Coat in a chic almond beige hue. This coat is generously padded with a down-feather filling, ensuring optimal insulation against the cold. Its quilted design not only adds a fashionable touch but also enhances warmth.',
      'Outer: 100% Polyamide',
      'Lining: 100% Polyamide & 100% Feather Down',
    ],
  },
  {
    name: 'Brunello Cucinelli',
    productName: 'Chelsea Ankle Boots',
    price: '990',
    src: 'https://shop.futugoapp.com/cdn/shop/products/45241_136970.jpg?v=1694007118&width=720',
    size: '44',
    color: 'Black',
    composition: [
      'Step out in style with these Brunello Cucinelli Elasticated-Panel Chelsea Ankle Boots in classic black. Crafted in Italy from premium calf suede and calf leather, these boots exude both quality and sophistication.',
      '100% Calf Suede',
      '100% Calf Leather',
      '100% Rubber',
      'Product ID: MZUPEAE818',
    ],
  },
  {
    name: 'Palm Angels',
    productName: 'Mirage Hoodie',
    price: '485',
    src: 'https://shop.futugoapp.com/cdn/shop/products/14072023_083.jpg?v=1693922296&width=720',
    size: 'M',
    color: 'White',
    composition: [
      'Elevate your casual wear with the Palm Angels Mirage Hoodie for women, offered in a crisp white hue. This slim-fit hoodie is meticulously crafted from comfortable cotton, ensuring a flattering silhouette and all-day comfort.',
      '100% Cotton',
      'Product ID: PWBB022E23FLE0010305',
      'Made in Portugal. ',
    ],
  },
  {
    name: 'Hogan',
    productName: 'Hyperlight Sneakers',
    price: '420',
    src: 'https://shop.futugoapp.com/cdn/shop/products/25057_62996.jpg?v=1692880644&width=720',
    size: '11',
    color: 'White/Black',
    composition: [
      `Introducing the Hogan Hyperlight Sneakers, a perfect fusion of style and comfort. Crafted with meticulous attention to detail, these sneakers offer a lightweight and modern design that's ideal for various occasions.`,
      '100% Calfskin',
      'Made in Italy.',
    ],
  },
  {
    name: 'Palm Angels',
    productName: 'Cotton Shirt',
    price: '895',
    src: 'https://shop.futugoapp.com/cdn/shop/products/14072023_096.jpg?v=1693920587&width=720',
    size: '48',
    color: 'Black',
    composition: [
      `Elevate your wardrobe with this sophisticated Palm Angels gray cotton shirt tailored for men. With a refined front button closure, this shirt exudes timeless style. It also features a chest pocket adorned with the brand's logo, long sleeves, and a classic collar for a polished look.`,
      '100% Cotton',
      'Product ID: PMES002E23FAB001-1103',
    ],
  },
  {
    name: 'Prada',
    productName: 'Printed Slub Canvas Top',
    price: '2300',
    src: 'https://shop.futugoapp.com/cdn/shop/products/06022022_057.jpg?v=1692874805&width=720',
    size: '42',
    color: 'White',
    composition: [
      `Elevate your style with the Prada Sleeveless Printed Flamed Top, adorned with captivating symbols of the marine world like anchors, roses, mermaids, and barracudas, reminiscent of sailor tattoos.`,
      '56% Linen',
      '44% Cotton',
    ],
  },
  {
    name: 'Jil Sander',
    productName: 'Silk Shirt',
    price: '1560',
    color: 'Green',
    size: '38',
    src: 'https://shop.futugoapp.com/cdn/shop/products/34337_113852.jpg?v=1692801954&width=720',
    composition: [
      `Introducing the Jil Sander Chinablue Silk Shirt, a luxurious addition to your wardrobe. Crafted from exquisite chinablue silk, this shirt features long sleeves and a classic crew neckline.`,
      '100% Silk',
      'Made in Italy',
    ],
  },
  {
    name: 'Stella McCartney',
    productName: 'Jacket',
    price: '1290',
    size: '44',
    color: 'BLack',
    src: 'https://shop.futugoapp.com/cdn/shop/products/34382_113263_b583635b-2869-40df-848e-9d6c2f8c3b9c.jpg?v=1692794083&width=720',
    composition: [
      `Elevate your formal ensemble with the Stella McCartney V-Neck Double-Breasted Blazer. This blazer features a stylish v-neck design and a double-breasted closure for a sophisticated look. `,
      '55% Polyester',
      '41% Wool',
      '4% Elastane',
      'Made in Italy',
    ],
  },
  {
    name: 'Stella McCartney',
    productName: 'Jeans',
    price: '550',
    size: '29',
    color: 'Blue',
    src: 'https://shop.futugoapp.com/cdn/shop/products/19122022_163.jpg?v=1692789735&width=720',
    composition: [
      `Experience timeless style with the Stella McCartney High-Rise Straight-Leg Jeans. Crafted from stretch-cotton denim in a classic blue hue, these jeans boast a monogram print that adds a touch of signature flair. The high-rise design is complemented by belt loops`,
      '98% Cotton',
      '2% Elastane',
      'Made in Portugal',
    ],
  },
  {
    name: 'Gianvito Rossi',
    productName: 'Gianvito Rossi',
    price: '890',
    color: 'Black',
    size: '38',
    src: 'https://shop.futugoapp.com/cdn/shop/products/26042023_010.jpg?v=1692789587&width=720',
    composition: [
      `Introducing Gianvito Rossi's 120mm Platform Pumps, a testament to meticulous craftsmanship and design expertise. Rooted in attention to detail and a thoughtful creative process, these pumps embody Gianvito Rossi's philosophy.`,
      'Sole: 100% Calf Leather ',
      'Outer: 100% Fabric',
      'Made in Italy',
    ],
  },
  {
    name: 'Maison Margiela',
    productName: '5AC Tote Bag',
    price: '1440',
    size: 'Unica',
    color: 'White',
    src: 'https://shop.futugoapp.com/cdn/shop/products/17082023_140.jpg?v=1692786521&width=720',
    composition: [
      '50% Fabric',
      '50% Calf Leather',
      'Depth: 12 cm / 4.72 in',
      'Height: 22 cm / 8.66 in',
      'Strap: 50 cm / 19.69 in',
      'Width: 15 cm / 5.91 in',
      'Made in Italy',
    ],
  },
  {
    name: 'Maison Margiela',
    productName: 'Distressed Check Cardigan',
    size: 'L',
    color: 'Blue',
    price: '1490',
    src: 'https://shop.futugoapp.com/cdn/shop/products/17082023_104.jpg?v=1692786474&width=720',
    composition: [
      `Add a touch of edgy style to your wardrobe with Maison Margiela's distressed check-pattern cardigan.`,
      '58% Mohair',
      '38% Polyamide',
      '4% Wool',
      'Dry Clean Only',
    ],
  },
  {
    name: 'Extreme Cashmere',
    productName: 'Papilli Cardigan',
    color: 'Red',
    size: 'Unica',
    price: '995',
    src: 'https://shop.futugoapp.com/cdn/shop/products/17082023_039.jpg?v=1692786464&width=720',
    composition: [
      `The Papilli cashmere cardigan by Extreme Cashmere effortlessly captures a slouchy chic aesthetic with its cozy and relaxed silhouette.`,
      '100% Cashmere',
      'Made in China',
    ],
  },
  {
    name: 'Dsquared2',
    productName: 'Denim Logo Shirt',
    color: 'Blue',
    size: '42',
    price: '540',
    src: 'https://shop.futugoapp.com/cdn/shop/products/36130_127029.jpg?v=1692705840&width=720',
    composition: [
      `Introducing the Navy Blue Denim Shirt by Dsquared2, a stylish piece crafted from cotton with a vintage effect.`,
      '98% Cotton',
      '2% Elastane',
    ],
  },
  {
    name: 'Fay',
    productName: 'Padded Jacket',
    price: '1100',
    color: 'Green',
    size: 'XL',
    src: 'https://shop.futugoapp.com/cdn/shop/products/30101_128479.jpg?v=1692705094&width=720',
    composition: [
      `The FAY Padded Jacket is a versatile and stylish outerwear piece. Designed for warmth and comfort, it features a padded construction that provides insulation against the cold.`,
      '100% Polyester',
      'Padding: 90% Down, 10% Feather',
      'Made in Italy',
    ],
  },
  {
    name: 'Giorgio Armani',
    productName: 'Geometric Sweater',
    size: '54',
    color: 'Mix',
    price: '1200',
    src: 'https://shop.futugoapp.com/cdn/shop/products/30775_91276.jpg?v=1692704811&width=720',
    composition: [
      `Upgrade your winter wardrobe with the Giorgio Armani Jacquard Geometric Sweater. This exquisite sweater features a captivating geometric jacquard pattern that adds a touch of modern elegance.`,
      'Outer: Wool 100%',
      'Inner: Silk 100%',
      'Made in Italy',
    ],
  },
  {
    name: 'Dsquared2',
    productName: 'Be Icon Bag',
    price: '475',
    size: 'Unica',
    color: 'Black',
    src: 'https://shop.futugoapp.com/cdn/shop/products/21122022_025.jpg?v=1692701164&width=720',
    composition: [
      `Introducing the Women's Shoulder Bag by Dsquared2, adorned with the iconic white "Icon" logo on the front. This versatile bag boasts both two handles and a strap closure for convenience and style.`,
      '100% Polyester',
    ],
  },

  {
    name: 'Gucci',
    productName: 'Rhyton Sneakers',
    price: '795',
    size: '10',
    color: 'Gray',
    src: 'https://shop.futugoapp.com/cdn/shop/products/09032023_292.jpg?v=1692626811&width=720',
    composition: [
      `Add a touch of luxury to your outfit with these Round Interlocking G Cotton Socks from Gucci. Made from soft cotton, these socks feature the iconic interlocking G logo in a round design.`,
      'Cotton 100%',
    ],
  },
  {
    name: 'P.A.R.O.S.H.',
    productName: 'Sequined Dress',
    price: '826',
    size: 'L',
    color: 'Gold',
    src: 'https://shop.futugoapp.com/cdn/shop/products/43366_137629.jpg?v=1692624168&width=720',
    composition: [
      `Make a stunning entrance with the P.A.R.O.S.H. Sequined Sleeveless Dress. Its shimmering brown sequin design catches the light for a captivating look. `,
      'Outer: 100% Sequin, 100% PVC, 90% Polyamide & 10% Elastane',
      'Lining: 90% Polyamide & 10% Elastane',
      'Dry Clean Only',
    ],
  },
  {
    name: 'Gucci',
    productName: 'Wallet',
    price: '580',
    size: 'Unica',
    color: 'Black/Gray',
    src: 'https://shop.futugoapp.com/cdn/shop/products/40296_134264.jpg?v=1692624014&width=720',
    composition: [
      `Elevate your accessory game with the exquisite Gucci wallet. Crafted with the finest materials and meticulous attention to detail, this wallet combines timeless elegance with modern functionality.`,
      'Outer: Leather 100%',
      'Lining: Leather 100%',
    ],
  },
];

export const secondCarusel = [
  {
    name: 'Maison Margiela',
    productName: '5AC Tote Bag',
    price: '1440',
    size: 'Unica',
    color: 'White',
    src: 'https://shop.futugoapp.com/cdn/shop/products/17082023_140.jpg?v=1692786521&width=720',
    composition: [
      '50% Fabric',
      '50% Calf Leather',
      'Depth: 12 cm / 4.72 in',
      'Height: 22 cm / 8.66 in',
      'Strap: 50 cm / 19.69 in',
      'Width: 15 cm / 5.91 in',
      'Made in Italy',
    ],
  },
  {
    name: 'Maison Margiela',
    productName: 'Distressed Check Cardigan',
    size: 'L',
    color: 'Blue',
    price: '1490',
    src: 'https://shop.futugoapp.com/cdn/shop/products/17082023_104.jpg?v=1692786474&width=720',
    composition: [
      `Add a touch of edgy style to your wardrobe with Maison Margiela's distressed check-pattern cardigan.`,
      '58% Mohair',
      '38% Polyamide',
      '4% Wool',
      'Dry Clean Only',
    ],
  },
  {
    name: 'Extreme Cashmere',
    productName: 'Papilli Cardigan',
    color: 'Red',
    size: 'Unica',
    price: '995',
    src: 'https://shop.futugoapp.com/cdn/shop/products/17082023_039.jpg?v=1692786464&width=720',
    composition: [
      `The Papilli cashmere cardigan by Extreme Cashmere effortlessly captures a slouchy chic aesthetic with its cozy and relaxed silhouette.`,
      '100% Cashmere',
      'Made in China',
    ],
  },
  {
    name: 'Dsquared2',
    productName: 'Denim Logo Shirt',
    color: 'Blue',
    size: '42',
    price: '540',
    src: 'https://shop.futugoapp.com/cdn/shop/products/36130_127029.jpg?v=1692705840&width=720',
    composition: [
      `Introducing the Navy Blue Denim Shirt by Dsquared2, a stylish piece crafted from cotton with a vintage effect.`,
      '98% Cotton',
      '2% Elastane',
    ],
  },
  {
    name: 'Fay',
    productName: 'Padded Jacket',
    price: '1100',
    color: 'Green',
    size: 'XL',
    src: 'https://shop.futugoapp.com/cdn/shop/products/30101_128479.jpg?v=1692705094&width=720',
    composition: [
      `The FAY Padded Jacket is a versatile and stylish outerwear piece. Designed for warmth and comfort, it features a padded construction that provides insulation against the cold.`,
      '100% Polyester',
      'Padding: 90% Down, 10% Feather',
      'Made in Italy',
    ],
  },
  {
    name: 'Giorgio Armani',
    productName: 'Geometric Sweater',
    size: '54',
    color: 'Mix',
    price: '1200',
    src: 'https://shop.futugoapp.com/cdn/shop/products/30775_91276.jpg?v=1692704811&width=720',
    composition: [
      `Upgrade your winter wardrobe with the Giorgio Armani Jacquard Geometric Sweater. This exquisite sweater features a captivating geometric jacquard pattern that adds a touch of modern elegance.`,
      'Outer: Wool 100%',
      'Inner: Silk 100%',
      'Made in Italy',
    ],
  },
  {
    name: 'Dsquared2',
    productName: 'Be Icon Bag',
    price: '475',
    size: 'Unica',
    coloe: 'Black',
    src: 'https://shop.futugoapp.com/cdn/shop/products/21122022_025.jpg?v=1692701164&width=720',
    composition: [
      `Introducing the Women's Shoulder Bag by Dsquared2, adorned with the iconic white "Icon" logo on the front. This versatile bag boasts both two handles and a strap closure for convenience and style.`,
      '100% Polyester',
    ],
  },

  {
    name: 'Gucci',
    productName: 'Rhyton Sneakers',
    price: '795',
    size: '10',
    color: 'Gray',
    src: 'https://shop.futugoapp.com/cdn/shop/products/09032023_292.jpg?v=1692626811&width=720',
    composition: [
      `Add a touch of luxury to your outfit with these Round Interlocking G Cotton Socks from Gucci. Made from soft cotton, these socks feature the iconic interlocking G logo in a round design.`,
      'Cotton 100%',
    ],
  },
  {
    name: 'P.A.R.O.S.H.',
    productName: 'Sequined Dress',
    price: '826',
    size: 'L',
    color: 'Gold',
    src: 'https://shop.futugoapp.com/cdn/shop/products/43366_137629.jpg?v=1692624168&width=720',
    composition: [
      `Make a stunning entrance with the P.A.R.O.S.H. Sequined Sleeveless Dress. Its shimmering brown sequin design catches the light for a captivating look. `,
      'Outer: 100% Sequin, 100% PVC, 90% Polyamide & 10% Elastane',
      'Lining: 90% Polyamide & 10% Elastane',
      'Dry Clean Only',
    ],
  },
  {
    name: 'Gucci',
    productName: 'Wallet',
    price: '580',
    size: 'Unica',
    color: 'Black/Gray',
    src: 'https://shop.futugoapp.com/cdn/shop/products/40296_134264.jpg?v=1692624014&width=720',
    composition: [
      `Elevate your accessory game with the exquisite Gucci wallet. Crafted with the finest materials and meticulous attention to detail, this wallet combines timeless elegance with modern functionality.`,
      'Outer: Leather 100%',
      'Lining: Leather 100%',
    ],
  },
];

export const firstCarusel = [
  {
    name: 'Parajumpers',
    productName: 'Janet Puffer Coat',
    price: '745',
    src: 'https://shop.futugoapp.com/cdn/shop/products/45660_137472.jpg?v=1693926500&width=720',
    size: 'S',
    color: 'Nude',
    composition: [
      'Stay warm and stylish with the Parajumpers Janet Oversized Puffer Coat in a chic almond beige hue. This coat is generously padded with a down-feather filling, ensuring optimal insulation against the cold. Its quilted design not only adds a fashionable touch but also enhances warmth.',
      '-Outer: 100% Polyamide',
      '-Lining: 100% Polyamide & 100% Feather Down',
    ],
  },
  {
    name: 'Brunello Cucinelli',
    productName: 'Chelsea Ankle Boots',
    price: '990',
    src: 'https://shop.futugoapp.com/cdn/shop/products/45241_136970.jpg?v=1694007118&width=720',
    size: '44',
    color: 'Black',
    composition: [
      'Step out in style with these Brunello Cucinelli Elasticated-Panel Chelsea Ankle Boots in classic black. Crafted in Italy from premium calf suede and calf leather, these boots exude both quality and sophistication.',
      '100% Calf Suede',
      '100% Calf Leather',
      '100% Rubber',
      'Product ID: MZUPEAE818',
    ],
  },
  {
    name: 'Palm Angels',
    productName: 'Mirage Hoodie',
    price: '485',
    src: 'https://shop.futugoapp.com/cdn/shop/products/14072023_083.jpg?v=1693922296&width=720',
    size: 'M',
    color: 'White',
    composition: [
      'Elevate your casual wear with the Palm Angels Mirage Hoodie for women, offered in a crisp white hue. This slim-fit hoodie is meticulously crafted from comfortable cotton, ensuring a flattering silhouette and all-day comfort.',
      '100% Cotton',
      'Product ID: PWBB022E23FLE0010305',
      'Made in Portugal. ',
    ],
  },
  {
    name: 'Hogan',
    productName: 'Hyperlight Sneakers',
    price: '420',
    src: 'https://shop.futugoapp.com/cdn/shop/products/25057_62996.jpg?v=1692880644&width=720',
    size: '11',
    color: 'White/Black',
    composition: [
      `Introducing the Hogan Hyperlight Sneakers, a perfect fusion of style and comfort. Crafted with meticulous attention to detail, these sneakers offer a lightweight and modern design that's ideal for various occasions.`,
      '100% Calfskin',
      'Made in Italy.',
    ],
  },
  {
    name: 'Palm Angels',
    productName: 'Cotton Shirt',
    price: '895',
    src: 'https://shop.futugoapp.com/cdn/shop/products/14072023_096.jpg?v=1693920587&width=720',
    size: '48',
    color: 'Black',
    composition: [
      `Elevate your wardrobe with this sophisticated Palm Angels gray cotton shirt tailored for men. With a refined front button closure, this shirt exudes timeless style. It also features a chest pocket adorned with the brand's logo, long sleeves, and a classic collar for a polished look.`,
      '100% Cotton',
      'Product ID: PMES002E23FAB001-1103',
    ],
  },
  {
    name: 'Prada',
    productName: 'Printed Slub Canvas Top',
    price: '2300',
    src: 'https://shop.futugoapp.com/cdn/shop/products/06022022_057.jpg?v=1692874805&width=720',
    size: '42',
    color: 'White',
    composition: [
      `Elevate your style with the Prada Sleeveless Printed Flamed Top, adorned with captivating symbols of the marine world like anchors, roses, mermaids, and barracudas, reminiscent of sailor tattoos.`,
      '56% Linen',
      '44% Cotton',
    ],
  },
  {
    name: 'Jil Sander',
    productName: 'Silk Shirt',
    price: '1560',
    color: 'Green',
    size: '38',
    src: 'https://shop.futugoapp.com/cdn/shop/products/34337_113852.jpg?v=1692801954&width=720',
    composition: [
      `Introducing the Jil Sander Chinablue Silk Shirt, a luxurious addition to your wardrobe. Crafted from exquisite chinablue silk, this shirt features long sleeves and a classic crew neckline.`,
      '100% Silk',
      'Made in Italy',
    ],
  },
  {
    name: 'Stella McCartney',
    productName: 'Jacket',
    price: '1290',
    size: '44',
    color: 'BLack',
    src: 'https://shop.futugoapp.com/cdn/shop/products/34382_113263_b583635b-2869-40df-848e-9d6c2f8c3b9c.jpg?v=1692794083&width=720',
    composition: [
      `Elevate your formal ensemble with the Stella McCartney V-Neck Double-Breasted Blazer. This blazer features a stylish v-neck design and a double-breasted closure for a sophisticated look. `,
      '55% Polyester',
      '41% Wool',
      '4% Elastane',
      'Made in Italy',
    ],
  },
  {
    name: 'Stella McCartney',
    productName: 'Jeans',
    price: '550',
    size: '29',
    color: 'Blue',
    src: 'https://shop.futugoapp.com/cdn/shop/products/19122022_163.jpg?v=1692789735&width=720',
    composition: [
      `Experience timeless style with the Stella McCartney High-Rise Straight-Leg Jeans. Crafted from stretch-cotton denim in a classic blue hue, these jeans boast a monogram print that adds a touch of signature flair. The high-rise design is complemented by belt loops`,
      '98% Cotton',
      '2% Elastane',
      'Made in Portugal',
    ],
  },
  {
    name: 'Gianvito Rossi',
    productName: 'Gianvito Rossi',
    price: '890',
    color: 'Black',
    size: '38',
    src: 'https://shop.futugoapp.com/cdn/shop/products/26042023_010.jpg?v=1692789587&width=720',
    composition: [
      `Introducing Gianvito Rossi's 120mm Platform Pumps, a testament to meticulous craftsmanship and design expertise. Rooted in attention to detail and a thoughtful creative process, these pumps embody Gianvito Rossi's philosophy.`,
      'Sole: 100% Calf Leather ',
      'Outer: 100% Fabric',
      'Made in Italy',
    ],
  },
];

export const hotDropsData = [
  {
    name: 'Test NFT #1',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    src: 'https://shop.futugoapp.com/cdn/shop/products/10675_81263.jpg?v=1693213172&width=720',
  },
  {
    name: 'Test NFT #1',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    src: 'https://images.unsplash.com/photo-1638913970675-b5ec36292665?ixlib=rb-1.2.1&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1332&q=80',
  },
  {
    name: 'Test NFT #1',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    src: 'https://images.unsplash.com/photo-1633250587603-42e4fd67f5a2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
  },
  {
    name: 'Test NFT #1',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    src: 'https://images.unsplash.com/photo-1614812513172-567d2fe96a75?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
  },
  {
    name: 'Test NFT #1',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    src: 'https://images.unsplash.com/photo-1541661538396-53ba2d051eed?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=627&q=80',
  },
  {
    name: 'Test NFT #1',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    src: 'https://images.unsplash.com/photo-1573221566340-81bdde00e00b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80',
  },
  {
    name: 'Test NFT #1',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    src: 'https://images.unsplash.com/flagged/photo-1567934150921-7632371abb32?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
  },
  {
    name: 'Test NFT #1',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    src: 'https://images.unsplash.com/photo-1559762717-99c81ac85459?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
  },
  {
    name: 'Test NFT #1',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    src: 'https://images.unsplash.com/photo-1608085575984-d61d8335340e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
  },
];
